// src/features/dsa/routes/DSA/0. Languages & Ecosystems/Frameworks/Frontend/Next.js/index.tsx
import { Fragment } from 'react'

import TopicPageShell from '@/features/dsa/components/TopicPageShell'
import { useTopicTabs } from '@/features/dsa/hooks/useTopicTabs'

import type { JSX } from 'react'

type DocSection = {
  id: string
  title: string
  paragraphs: readonly string[]
}

type ExampleSnippet = {
  label: string
  code: string
}

type ExampleSection = {
  id: string
  title: string
  description: string
  snippets: readonly ExampleSnippet[]
  takeaway: string
}

type GlossaryTerm = {
  term: string
  definition: string
}

type TabId = 'big-picture' | 'core-concepts' | 'examples' | 'glossary'

const bigPictureSections: readonly DocSection[] = [
  {
    id: 'bp-overview',
    title: 'Overview',
    paragraphs: [
      'Next.js is a React framework for building full-stack web applications. It provides file-system routing, server and client rendering strategies, route handlers, layouts, data-fetching patterns, middleware, deployment-aware optimizations, and a coordinated application model around React.',
      'In practice, Next.js is used for marketing sites, content platforms, e-commerce fronts, dashboards, SaaS products, internal tools, documentation systems, and large production web applications that need more than plain React components.',
      'This help-style version expands the original placeholder into a fuller reference covering App Router mental model, server and client components, route handlers, caching, rendering, navigation, use cases, tradeoffs, examples, and glossary terms.',
    ],
  },
  {
    id: 'bp-why-next',
    title: 'Why Teams Reach For Next.js',
    paragraphs: [
      'Next.js matters because it turns React from a UI library into a broad application platform. Instead of leaving routing, rendering mode, request handling, bundling, image optimization, and deployment patterns as separate decisions, it offers one framework story for many of them.',
      'The practical appeal is consistency. Teams can adopt a route-aware, server-capable React stack with built-in conventions rather than stitching together a large set of packages and internal rules for every project.',
    ],
  },
  {
    id: 'bp-what-it-optimizes',
    title: 'What Next.js Optimizes For',
    paragraphs: [
      'Next.js optimizes for React application development with strong production-focused defaults. It tries to make routing, rendering, caching, navigation, bundling, and server integration feel like one framework problem instead of many disconnected infrastructure problems.',
      'It also optimizes for deployment and runtime flexibility. Different routes and components can participate in different rendering and caching strategies, and the framework is built with server execution, streaming, and route-aware optimization in mind.',
    ],
  },
  {
    id: 'bp-react-relationship',
    title: 'Relationship to React',
    paragraphs: [
      'Next.js is built on React, but it is not just React with a router. The framework defines how React is structured into routes, layouts, server and client boundaries, request handlers, and deployment behavior.',
      'This distinction matters because a Next.js codebase often feels substantially different from plain React. The component model is still React, but much of the architecture is decided by the framework.',
    ],
  },
  {
    id: 'bp-app-router',
    title: 'Why the App Router Matters',
    paragraphs: [
      'Current Next.js guidance centers on the App Router. It is the newer router model that uses React Server Components, layouts, route segments, loading states, error boundaries, route handlers, and server-side mutation patterns as first-class architecture concepts.',
      'This changes how teams think about React applications. Instead of a mostly client-driven route tree with optional SSR around it, the framework treats server rendering and route-segment boundaries as core parts of normal app structure.',
    ],
  },
  {
    id: 'bp-pages-router',
    title: 'Pages Router Still Exists',
    paragraphs: [
      'Next.js still supports the older Pages Router, and it remains relevant in existing codebases. However, the App Router is the main direction for newer framework features and for the current mental model discussed in official documentation.',
      'That means teams maintaining older projects may need to understand both models. The architectural center of new greenfield work is usually the App Router, while legacy products may still use Pages Router conventions.',
    ],
  },
  {
    id: 'bp-where-it-fits',
    title: 'Where Next.js Fits Well',
    paragraphs: [
      'Next.js is a strong fit for full-stack React products that need route-level structure, SSR or hybrid rendering, SEO-sensitive pages, React Server Component workflows, and a deployment-aware platform story.',
      'It is also a common organizational default when teams want a mainstream React framework with strong ecosystem gravity and a broad set of built-in capabilities.',
    ],
  },
  {
    id: 'bp-common-misreadings',
    title: 'Common Misreadings',
    paragraphs: [
      'A common mistake is to treat Next.js as if it were just React plus file-based routing. That misses the importance of server and client component boundaries, cache behavior, route handlers, and rendering policy.',
      'Another mistake is to discuss the framework without naming which router model is being used. Many historical blog posts and code examples are Pages Router based, while many modern patterns assume the App Router.',
    ],
  },
  {
    id: 'bp-takeaways',
    title: 'Quick Takeaways',
    paragraphs: [
      'Next.js centers on React plus a full application framework layer for routing, rendering, server integration, and deployment-aware optimization.',
      'Its main strengths are integrated architecture, large ecosystem gravity, strong React alignment, and flexible rendering and caching options.',
      'Its main tradeoffs are framework complexity, the need to understand server and client boundaries carefully, and the fact that framework behavior can be more sophisticated than plain React teams initially expect.',
    ],
  },
] as const

const coreConceptSections: readonly DocSection[] = [
  {
    id: 'core-mental-model',
    title: 'Mental Model',
    paragraphs: [
      'Next.js asks developers to think in terms of routes, layouts, and server-aware rendering boundaries rather than only in terms of client-side components. The route tree becomes a major architectural tool, and server work is not an afterthought layered on top of a purely client app.',
      'This is especially true in the App Router. Pages and layouts are server-first by default, and interactivity is layered in with explicit client component boundaries where needed.',
    ],
  },
  {
    id: 'core-app-router',
    title: 'App Router',
    paragraphs: [
      'The App Router is the newer file-system router in Next.js and the main framework direction in the current docs. It uses route segments, layouts, React Server Components, route handlers, loading states, and error boundaries as core building blocks.',
      'This gives the framework a route-centered architecture where navigation, rendering, and data loading are shaped by the file structure inside the `app/` directory.',
    ],
  },
  {
    id: 'core-project-structure',
    title: 'Project Structure and File Conventions',
    paragraphs: [
      'Next.js uses file conventions such as `app/`, `page.tsx`, `layout.tsx`, `loading.tsx`, `error.tsx`, and `route.ts` to define route behavior and UI structure. The framework reads meaning from those files rather than asking teams to register every behavior manually.',
      'This convention-first design reduces setup and helps teams navigate codebases more quickly, but it also means developers must learn what each special file means in the framework lifecycle.',
    ],
  },
  {
    id: 'core-layouts',
    title: 'Layouts and Route Segments',
    paragraphs: [
      'Layouts are a major part of the App Router. Shared UI shells can persist across navigation while only the changed route segments rerender. This helps route hierarchy shape both user experience and application structure.',
      'The architectural effect is significant: a route tree becomes a composition model for shared shells, nested content, loading states, and cache reuse rather than only a URL mapping table.',
    ],
  },
  {
    id: 'core-server-client',
    title: 'Server and Client Components',
    paragraphs: [
      'In the App Router, pages and layouts are Server Components by default. They can render on the server, fetch data directly, participate in streaming, and avoid sending unnecessary component logic to the client.',
      'When a component needs state, event handlers, lifecycle logic, or browser APIs, it must become a Client Component through the `use client` directive. That boundary is one of the most important architectural decisions in modern Next.js.',
    ],
  },
  {
    id: 'core-boundaries',
    title: 'Why the Boundary Matters',
    paragraphs: [
      'The server and client boundary is not just a code-style preference. It determines bundle size, execution environment, data access patterns, and how much JavaScript the browser needs to download and run.',
      'Good Next.js architecture usually keeps as much as practical on the server while moving only truly interactive UI logic into client components.',
    ],
  },
  {
    id: 'core-data-fetching',
    title: 'Data Fetching in the App Router',
    paragraphs: [
      'A major shift in Next.js is that data can be fetched directly in Server Components using normal async patterns. This keeps server-owned data loading close to the route or component that needs it and can reduce the amount of client fetch orchestration required.',
      'The framework also layers caching and revalidation behavior on top of data fetching, so teams need to understand not only how to fetch data, but how that data is cached and refreshed.',
    ],
  },
  {
    id: 'core-caching',
    title: 'Caching Model',
    paragraphs: [
      'Next.js has a sophisticated caching model involving route output, fetched data, and client-side router behavior. The practical implication is that route performance and freshness depend on understanding what is cached, where it is cached, and how revalidation happens.',
      "This is one of the framework's biggest strengths and one of its main sources of confusion. Teams that ignore caching semantics often misread why a route is static, dynamic, reused, or refreshed.",
    ],
  },
  {
    id: 'core-navigation',
    title: 'Navigation, Prefetching, and Partial Rendering',
    paragraphs: [
      'Next.js uses built-in navigation with route-aware prefetching and partial rendering behavior. Shared layouts can remain mounted, and navigation often reuses cached route information to make transitions feel faster and more app-like.',
      "This means navigation is not only a router concern. It is directly tied to the framework's route segmentation and cache behavior.",
    ],
  },
  {
    id: 'core-loading-error',
    title: 'Loading and Error Boundaries',
    paragraphs: [
      'App Router conventions such as `loading.tsx` and `error.tsx` give routes explicit places for pending and failure states. This helps teams keep fallback UI and error handling aligned with route structure instead of scattering them through many components.',
      'The practical benefit is clarity. A route segment can define how it loads and how it fails as part of its normal module structure.',
    ],
  },
] as const

const coreConceptSectionsContinued: readonly DocSection[] = [
  {
    id: 'core-route-handlers',
    title: 'Route Handlers',
    paragraphs: [
      'Route Handlers in the App Router allow developers to define request handlers with Web Request and Response APIs inside the `app/` directory. They are the modern framework answer for custom backend endpoints associated with a route tree.',
      'This gives Next.js a native server endpoint story inside the application framework instead of forcing every project to stand up a separate API layer for simple integrated server logic.',
    ],
  },
  {
    id: 'core-server-actions',
    title: 'Server Functions and Mutations',
    paragraphs: [
      'Modern Next.js also uses server-side function patterns for mutations and server-executed logic. This reflects the broader direction of keeping more application behavior close to the server while letting client components trigger server work where needed.',
      'The key engineering question is not merely whether a mutation works, but whether the team has chosen the right boundary between server-owned logic and client-owned interactivity.',
    ],
  },
  {
    id: 'core-rendering-modes',
    title: 'Static, Dynamic, and Streaming Rendering',
    paragraphs: [
      'Next.js supports static generation, dynamic rendering, streaming, and mixed route behavior depending on what the route needs. Different data access patterns and configuration choices can move a route toward static or request-time rendering.',
      'That flexibility is powerful because a marketing page and a personalized dashboard do not need the same runtime policy. It also means teams should be deliberate about route behavior instead of assuming every page is rendered the same way.',
    ],
  },
  {
    id: 'core-middleware',
    title: 'Middleware and Request Flow',
    paragraphs: [
      'Next.js includes middleware capabilities that allow request-time logic such as redirects, rewrites, or authentication-related checks to run before a route resolves. This lets some cross-cutting behavior live near the edge of the request lifecycle.',
      'Teams should still use middleware judiciously. It is powerful, but it is best reserved for concerns that truly belong at the request boundary rather than in component code.',
    ],
  },
  {
    id: 'core-assets-optimization',
    title: 'Built-In Optimization Features',
    paragraphs: [
      'Next.js includes built-in features such as the `Link` component, image optimization, font tooling, code splitting, and route-aware bundling behavior. These are part of why the framework is often chosen for production-facing web apps rather than only for component rendering.',
      'The important point is that the framework tries to turn common web performance work into platform defaults, though teams still need to understand the tradeoffs and operational impact of those defaults.',
    ],
  },
  {
    id: 'core-typescript',
    title: 'TypeScript and Tooling',
    paragraphs: [
      'Next.js works closely with TypeScript, modern bundling, and React-aware linting and build workflows. In practice, many teams experience the framework as a coordinated toolchain as much as a runtime.',
      'That coordination is useful, but it also means framework upgrades and feature adoption can affect many layers of the project at once, including routing, build output, and runtime behavior.',
    ],
  },
  {
    id: 'core-ecosystem',
    title: 'Ecosystem and Platform Gravity',
    paragraphs: [
      'Next.js sits at the center of a large part of the React framework ecosystem. Many tutorials, templates, deployment workflows, hosting integrations, and adjacent tools assume or directly target Next.js.',
      'That ecosystem gravity is a major strength for hiring, support, and package compatibility. It can also create pressure to use the framework even when a narrower or simpler architecture might be sufficient.',
    ],
  },
  {
    id: 'core-pages-router',
    title: 'Pages Router in Existing Codebases',
    paragraphs: [
      'The Pages Router still matters because many production applications were built with it and continue to run successfully. Concepts such as `pages/`, `getServerSideProps`, and API routes remain relevant in maintenance and migration work.',
      'The important practical point is to avoid mixing mental models accidentally. App Router and Pages Router codebases often solve similar problems in meaningfully different ways.',
    ],
  },
  {
    id: 'core-use-cases',
    title: 'Use Cases',
    paragraphs: [
      'Next.js is frequently used for content-rich sites, e-commerce fronts, SaaS apps, admin panels, documentation, dashboards, and products that need a React-first framework with SSR or hybrid rendering support.',
      'It is also a common organizational default when teams want a broad React platform with strong deployment and tooling support rather than hand-assembling the entire app stack.',
    ],
  },
  {
    id: 'core-tradeoffs',
    title: 'Tradeoffs',
    paragraphs: [
      'Next.js offers a lot, but it asks teams to understand a relatively large framework surface. Routing conventions, server and client boundaries, cache semantics, route handlers, and rendering modes create real conceptual weight compared with plain React.',
      'Another tradeoff is that framework defaults can interact in subtle ways. Developers may need to understand why data is cached, why a route became dynamic, or why a component must be client-only, rather than assuming every issue is just ordinary React behavior.',
    ],
  },
  {
    id: 'core-compare',
    title: 'Compare and Contrast References',
    paragraphs: [
      'Next.js is commonly compared with plain React for framework integration versus library flexibility, with Remix for broad platform scope versus a more web-request-centered full-stack model, and with Nuxt for how React and Vue ecosystems approach integrated application frameworks.',
      'These comparisons help position Next.js correctly: it is the mainstream full-stack React framework choice for many teams, not just a small routing addon on top of React.',
    ],
  },
] as const
const coreConceptSectionsMerged: readonly DocSection[] = [
  ...coreConceptSections,
  ...coreConceptSectionsContinued,
]

const examples: readonly ExampleSection[] = [
  {
    id: 'examples-page',
    title: 'Server Component Page',
    description:
      'In the App Router, a page can be a Server Component by default and fetch data directly on the server without adding a client-side fetching layer first.',
    snippets: [
      {
        label: 'app/products/page.tsx',
        code: `async function getProducts() {
  const response = await fetch('https://example.com/api/products')
  return response.json()
}

export default async function ProductsPage() {
  const products = await getProducts()

  return (
    <ul>
      {products.map((product: { id: string; name: string }) => (
        <li key={product.id}>{product.name}</li>
      ))}
    </ul>
  )
}`,
      },
    ],
    takeaway:
      'A major Next.js mental shift is that many route-level data needs can stay on the server by default instead of being orchestrated through client hooks first.',
  },
  {
    id: 'examples-client',
    title: 'Client Component Boundary',
    description:
      'When interactivity, state, or browser APIs are needed, a component becomes client-side through the `use client` directive.',
    snippets: [
      {
        label: 'app/components/counter.tsx',
        code: `'use client'


export default function Counter() {
  const [count, setCount] = useState(0)

  return (
    <button onClick={() => setCount((value) => value + 1)}>
      Count: {count}
    </button>
  )
}`,
      },
    ],
    takeaway:
      'Client components are opt-in in the App Router. The boundary should be drawn intentionally because it changes execution environment and bundle cost.',
  },
  {
    id: 'examples-layout',
    title: 'Layout and Nested Route Shape',
    description:
      "Layouts are persistent route shells in the App Router. They are one of the framework's main architectural tools for shared structure and partial rendering.",
    snippets: [
      {
        label: 'app/dashboard/layout.tsx',
        code: `export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main>
      <aside>Dashboard navigation</aside>
      <section>{children}</section>
    </main>
  )
}`,
      },
      {
        label: 'app/dashboard/page.tsx',
        code: `export default function DashboardPage() {
  return <h1>Dashboard</h1>
}`,
      },
    ],
    takeaway:
      'In Next.js, route hierarchy is not only about URLs. It also defines persistent layout structure and what parts of the UI can be reused across navigation.',
  },
  {
    id: 'examples-route-handler',
    title: 'Route Handler Example',
    description:
      'Route Handlers provide an in-framework server endpoint model using Web Request and Response APIs inside the App Router.',
    snippets: [
      {
        label: 'app/api/products/route.ts',
        code: `export async function GET() {
  return Response.json([
    { id: '1', name: 'Keyboard' },
    { id: '2', name: 'Monitor' },
  ])
}`,
      },
    ],
    takeaway:
      'This keeps simple backend endpoints close to the app without requiring a separate API project for every server interaction.',
  },
  {
    id: 'examples-architecture',
    title: 'Architecture Snapshot',
    description:
      'A typical modern Next.js application uses the App Router as the organizing center for rendering, routing, server work, and navigation behavior.',
    snippets: [
      {
        label: 'Common Stack',
        code: `React for component authoring
App Router for route segments, layouts, loading states, and route handlers
Server Components by default for route-level rendering and data access
Client Components only where interactivity or browser APIs are required
Framework-managed caching, prefetching, and route-aware navigation`,
      },
    ],
    takeaway:
      'Next.js works best when the team treats it as a full framework with explicit server and client boundaries, not merely as React with nicer routing.',
  },
] as const

const glossaryTerms: readonly GlossaryTerm[] = [
  {
    term: 'Next.js',
    definition:
      'A React framework for building full-stack web applications with routing, rendering, server integration, and deployment-aware optimization.',
  },
  {
    term: 'App Router',
    definition:
      'The newer Next.js router model built around route segments, layouts, React Server Components, and file conventions in the `app/` directory.',
  },
  {
    term: 'Pages Router',
    definition:
      'The older Next.js router model based on the `pages/` directory, still supported and common in existing production codebases.',
  },
  {
    term: 'Server Component',
    definition:
      'A React component rendered on the server by default in the Next.js App Router, useful for server-side data access and reducing client bundle work.',
  },
  {
    term: 'Client Component',
    definition:
      'A React component marked with `use client` so it can use state, effects, event handlers, and browser APIs.',
  },
  {
    term: 'Route segment',
    definition:
      'A portion of the route tree in the App Router that can define layouts, pages, loading states, and related behavior.',
  },
  {
    term: 'Layout',
    definition:
      'A shared route shell that can persist across navigation and wrap nested route content.',
  },
  {
    term: 'Route Handler',
    definition:
      'A request handler inside the App Router, typically defined in `route.ts`, that uses Web Request and Response APIs.',
  },
  {
    term: 'Streaming',
    definition:
      'A rendering strategy where the server sends parts of the response as they become ready instead of waiting for the entire page to finish.',
  },
  {
    term: 'Prefetching',
    definition:
      'The framework behavior of loading route information ahead of navigation to make transitions feel faster.',
  },
  {
    term: 'Router cache',
    definition:
      'A client-side cache used by Next.js to store route-related payloads and improve navigation behavior.',
  },
  {
    term: 'Revalidation',
    definition:
      'The process of refreshing cached route or data output so the application reflects newer server state.',
  },
  {
    term: 'Middleware',
    definition:
      'Request-bound logic that runs before a route resolves, often used for redirects, rewrites, or access control checks.',
  },
  {
    term: 'Loading UI',
    definition:
      'A route-segment fallback state, often defined through `loading.tsx`, shown while server work is still in progress.',
  },
  {
    term: 'Error boundary',
    definition:
      'A route-segment error surface, often defined through `error.tsx`, used when rendering or data work fails.',
  },
  {
    term: 'Route segment config',
    definition:
      'Per-route configuration that influences rendering or runtime behavior in the App Router.',
  },
] as const

const tabs: Array<{ id: TabId; label: string }> = [
  { id: 'big-picture', label: 'The Big Picture' },
  { id: 'core-concepts', label: 'Core Concepts' },
  { id: 'examples', label: 'Examples' },
  { id: 'glossary', label: 'Glossary' },
]

const sectionLinks: Record<TabId, Array<{ id: string; label: string }>> = {
  'big-picture': bigPictureSections.map((section) => ({ id: section.id, label: section.title })),
  'core-concepts': coreConceptSectionsMerged.map((section) => ({
    id: section.id,
    label: section.title,
  })),
  examples: examples.map((section) => ({ id: section.id, label: section.title })),
  glossary: [{ id: 'glossary-terms', label: 'Terms' }],
}

export default function Counter(): JSX.Element {
  const { activeTab, setActiveTab, handleMinimize } = useTopicTabs({
    tabs,
    pageTitle: 'Next.js',
    defaultTab: 'big-picture',
  })

  return (
    <TopicPageShell
      title="Next.js"
      tabs={tabs}
      activeTab={activeTab}
      onTabChange={setActiveTab}
      tocLinks={sectionLinks[activeTab]}
      onMinimize={handleMinimize}
    >
      <h1 className="bin98-doc-title">Next.js</h1>
      <p className="next-js-help-doc-subtitle">
        Manual-style reference covering overview, App Router, server and client components, route
        handlers, caching, rendering strategies, tradeoffs, and practical examples.
      </p>

      {activeTab === 'big-picture' &&
        bigPictureSections.map((section, index) => (
          <Fragment key={section.id}>
            <section id={section.id} className="bin98-section">
              <h2 className="bin98-heading">{section.title}</h2>
              {section.paragraphs.map((paragraph) => (
                <p key={paragraph}>{paragraph}</p>
              ))}
            </section>
            {index < bigPictureSections.length - 1 && <hr className="bin98-divider" />}
          </Fragment>
        ))}

      {activeTab === 'core-concepts' &&
        coreConceptSectionsMerged.map((section) => (
          <section key={section.id} id={section.id} className="bin98-section">
            <h2 className="bin98-heading">{section.title}</h2>
            {section.paragraphs.map((paragraph) => (
              <p key={paragraph}>{paragraph}</p>
            ))}
          </section>
        ))}

      {activeTab === 'examples' &&
        examples.map((example) => (
          <section key={example.id} id={example.id} className="bin98-section">
            <h2 className="bin98-heading">{example.title}</h2>
            <p>{example.description}</p>
            {example.snippets.map((snippet) => (
              <Fragment key={`${example.id}-${snippet.label}`}>
                <h3 className="bin98-subheading">{snippet.label}</h3>
                <div className="bin98-codebox">
                  <code>{snippet.code}</code>
                </div>
              </Fragment>
            ))}
            <p>
              <strong>Takeaway:</strong> {example.takeaway}
            </p>
          </section>
        ))}

      {activeTab === 'glossary' && (
        <section id="glossary-terms" className="bin98-section">
          <h2 className="bin98-heading">Glossary</h2>
          {glossaryTerms.map((item) => (
            <p key={item.term}>
              <strong>{item.term}:</strong> {item.definition}
            </p>
          ))}
        </section>
      )}
    </TopicPageShell>
  )
}

// src/features/dsa/routes/DSA/0. Languages & Ecosystems/Web Technologies/Frontend/Vue.js/index.tsx
import TopicPageShell from '@/features/dsa/components/TopicPageShell'
import { useTopicTabs } from '@/features/dsa/hooks/useTopicTabs'

import type { JSX } from 'react'

type TabId = 'big-picture' | 'core-concepts' | 'examples' | 'glossary'

const overviewSections = [
  {
    title: 'What Vue.js is',
    body: 'Vue.js is a frontend framework for building user interfaces through components, reactive state, declarative templates, and a cohesive tooling ecosystem. It aims to be approachable for smaller projects while still scaling to substantial applications through component composition, the Composition API, routing, state tools, and framework companions such as Nuxt.',
  },
  {
    title: 'Why Vue.js matters',
    body: 'Vue matters because it offered a frontend model that many teams found easier to approach than some alternatives while still supporting professional application architecture. Its template syntax, reactive system, single-file components, and gradual-adoption story helped it become one of the major frontend ecosystems.',
  },
  {
    title: 'How to think about it',
    body: 'The useful mental model is that Vue sits between lightweight UI authoring and structured application development. It provides a strong component model, built-in reactivity, clear template syntax, and official companion libraries without forcing every application into one rigid shape. That balance is a major part of its appeal.',
  },
  {
    title: 'Where it fits best',
    body: 'Vue fits well for interactive web applications, dashboards, product surfaces, design-system-driven work, and teams that want a cohesive but approachable component framework. It is also a strong choice when a project may start small and grow over time without abandoning its initial UI model.',
  },
]

const whyItMatters = [
  'It combines a strong component model with an approachable reactive programming style.',
  'It offers an official ecosystem for routing, state, and tooling without requiring excessive ceremony.',
  'It supports both gradual adoption and large application architecture.',
  'It provides single-file components that colocate logic, template, and styles in a readable way.',
  'It remains one of the central alternatives to React and Angular in frontend engineering.',
]

const historicalContext = [
  {
    title: 'Frontend teams wanted structure without excessive overhead',
    detail:
      'As frontend systems became larger, teams looked for frameworks that could provide reactivity, component composition, and maintainable UI structure without forcing every project into highly complex patterns from the beginning. Vue gained traction by offering that middle ground.',
  },
  {
    title: 'Templates and reactivity remained a deliberate part of the model',
    detail:
      'Where some ecosystems leaned more heavily into JavaScript-driven render code, Vue retained a strong template-driven identity. That made it feel familiar to many web developers while still offering modern component architecture and a reactive data model.',
  },
  {
    title: 'The ecosystem matured around official companions',
    detail:
      'Vue became more viable for large applications as companion libraries such as Vue Router, Pinia, and later Nuxt gave teams more consistent answers for routing, state, and application delivery. This helped the ecosystem feel more complete without losing its relatively approachable core.',
  },
  {
    title: 'The Composition API broadened how Vue code is organized',
    detail:
      'Earlier Vue code often centered heavily on the Options API, while newer Vue applications often use the Composition API for reusable logic and more flexible component organization. Understanding modern Vue means understanding both the reactive model and how those APIs shape code structure.',
  },
]

const bigPictureThemes = [
  {
    title: 'Vue balances approachability with application depth',
    body: 'Vue is often praised because it can feel easy to start with while still supporting more advanced frontend architecture. That does not mean complexity disappears as an app grows, but it does mean the framework tries to let teams adopt more structure as they need it rather than all at once.',
  },
  {
    title: 'Reactivity is central to the authoring model',
    body: 'Vue applications revolve around reactive state and derived rendering. Understanding refs, reactive objects, computed values, and watchers is crucial because these concepts shape how components communicate, update, and stay consistent over time.',
  },
  {
    title: 'Templates remain a first-class way to describe UI',
    body: 'Vue treats templates as a core interface for expressing UI structure, bindings, conditionals, and repetition. Teams that prefer a clear separation between stateful logic and declarative markup often find this model easier to scan than more code-centric alternatives.',
  },
  {
    title: 'The framework helps, but architecture still matters',
    body: 'Vue provides a coherent set of concepts, but applications still require careful decisions about component boundaries, state ownership, async data, routing, and performance. A pleasant syntax does not automatically prevent overgrown components or unclear data flow.',
  },
]

const keyTakeaways = [
  'Vue.js is a component framework centered on reactivity, templates, and single-file components.',
  'Its main value is the balance between developer approachability and real application capability.',
  'Reactive state management is one of the core ideas teams must understand to use Vue well.',
  'The framework works best when components, stores, and derived state have clear boundaries.',
  'Vue often becomes even more powerful when paired with official ecosystem tools such as Vue Router, Pinia, and Nuxt.',
]

const topicSignals = [
  {
    title: 'Choose Vue when the team wants a coherent but approachable framework',
    body: 'If the team wants component architecture, reactive state, and official ecosystem support without assembling every concern independently, Vue is a strong candidate.',
  },
  {
    title: 'Choose Vue when template-driven UI is a good fit',
    body: 'Teams that prefer a declarative template model for rendering, conditions, loops, and bindings often find Vue comfortable because the framework keeps that style central rather than incidental.',
  },
  {
    title: 'Choose Vue when gradual adoption matters',
    body: 'Vue can work for both focused UI islands and larger applications, which makes it useful in codebases that may grow over time or be integrated incrementally into an existing frontend landscape.',
  },
  {
    title: 'Avoid treating Vue syntax as the whole framework',
    body: 'Teams sometimes learn template syntax quickly but never fully internalize reactivity, state boundaries, routing structure, or async coordination. That usually leads to apps that feel easy at first but become tangled later.',
  },
]

const coreFoundations = [
  {
    title: 'Single-file components',
    body: 'Vue commonly uses single-file components that colocate template, script, and styles. This can improve readability because UI structure and component logic stay together, as long as components remain focused instead of growing into broad multipurpose files.',
  },
  {
    title: 'Refs, reactive objects, and computed values',
    body: 'Vue reactivity revolves around reactive primitives such as refs and reactive objects, alongside computed values for derived state. Developers need to understand these tools because they determine how data changes propagate through templates and component trees.',
  },
  {
    title: 'Templates, directives, and declarative UI',
    body: 'Vue templates support conditionals, lists, bindings, event handlers, and directives in a way that keeps render structure readable. This helps teams keep UI logic close to the markup it affects instead of scattering everything across imperative update code.',
  },
  {
    title: 'Composition API and reusable logic',
    body: 'Modern Vue often uses the Composition API to extract and organize stateful logic. This makes reusable patterns easier to share across components, but it still requires discipline so composables remain cohesive rather than becoming vague helper collections.',
  },
  {
    title: 'State flow and ownership',
    body: 'Vue still benefits from clear state ownership even though the reactivity model can feel flexible. Props, emits, composables, and stores all have roles, and confusion arises when teams blur them without deciding which layer actually owns each concern.',
  },
]

const frameworkFeatures = [
  {
    title: 'Composition API and composables',
    body: 'The Composition API gives Vue a flexible way to organize reusable stateful behavior through refs, computed values, watchers, and custom composables. This helps larger applications avoid some of the limitations of purely options-based organization while preserving the Vue reactive model.',
  },
  {
    title: 'Official router and state ecosystem',
    body: 'Vue Router and Pinia give the ecosystem coherent answers for navigation and shared state. This matters because teams can stay within a fairly consistent design vocabulary instead of assembling many unrelated libraries for essential application concerns.',
  },
  {
    title: 'Directives, bindings, and template ergonomics',
    body: 'Vue includes strong first-class support for conditional rendering, loops, event handling, model binding, and custom directives. These features make common interface behaviors easy to express directly in the template without requiring a large amount of custom ceremony.',
  },
  {
    title: 'Scoped styles and component locality',
    body: 'Vue single-file components can keep styles close to the component that owns them. This helps local reasoning and reduces naming collisions, although larger design systems still need shared tokens, consistency rules, and intentional styling architecture.',
  },
  {
    title: 'Nuxt compatibility for application-level architecture',
    body: 'Vue can stand alone as a UI framework, but it also pairs naturally with Nuxt when teams need routing, server rendering, static generation, and fuller application structure. This makes Vue adaptable across both client-focused and hybrid delivery models.',
  },
]

const runtimeAndOperations = [
  {
    title: 'Reactive convenience still needs discipline',
    body: 'Vue makes state changes easy to express, but reactive convenience can become confusion if teams do not keep track of which state is local, derived, shared, or persisted. Clear ownership remains important even when the API feels smooth.',
  },
  {
    title: 'Watchers and side effects can be overused',
    body: 'Watchers are useful when code must react to changing state, but they can also become a source of hidden coupling if teams use them instead of modeling derived data more directly. A healthy Vue codebase tends to use watchers intentionally rather than as a default answer to every dependency problem.',
  },
  {
    title: 'Bundle size and third-party cost still matter',
    body: 'Vue itself does not determine total frontend performance. UI kits, charts, editors, and large utility packages can still dominate browser cost. Teams should evaluate the full dependency surface rather than assuming framework choice alone guarantees speed.',
  },
  {
    title: 'Observability and profiling still matter',
    body: 'Large Vue applications still need debugging discipline, render inspection, error reporting, and performance monitoring. Reactive systems can hide unexpected update paths, so teams benefit from tooling that reveals which state changes drive which UI changes.',
  },
]

const ecosystemUses = [
  {
    title: 'Interactive product interfaces',
    body: 'Vue is common in dashboards, management tools, commerce interfaces, content editing systems, and other products where components, reactive state, and reusable UI patterns are central to daily development.',
  },
  {
    title: 'Teams that want a coherent official ecosystem',
    body: 'Some teams choose Vue because they prefer a framework ecosystem with strong official companions rather than a more fragmented stack assembly process. That can reduce decision overhead and make architecture feel more consistent.',
  },
  {
    title: 'Projects that may start small and expand',
    body: 'Vue often works well for projects that begin as focused interfaces or embed surfaces and later grow into more substantial applications, because the framework supports both lighter use and larger structured patterns.',
  },
  {
    title: 'Hybrid apps through Nuxt',
    body: 'When paired with Nuxt, Vue becomes part of a broader application model that supports server rendering, route-level data, and deployment-aware behavior. This makes Vue relevant not only for client-side apps but also for document-driven web applications.',
  },
]

const comparisons = [
  {
    title: 'Vue versus React',
    body: 'Both frameworks support component-driven development, but Vue emphasizes templates, official ecosystem companions, and a different reactive programming style, while React leans more heavily into JavaScript-centric composition and a broader surrounding ecosystem.',
  },
  {
    title: 'Vue versus Angular',
    body: 'Angular offers a more opinionated application framework with stronger built-in structure, while Vue often feels lighter and more incrementally adoptable. The tradeoff is broader framework integration versus a more flexible and approachable starting point.',
  },
  {
    title: 'Vue versus Svelte',
    body: 'Svelte pushes more work into compilation and often feels even lighter in authoring and runtime shape, while Vue keeps a stronger established runtime ecosystem and a long-matured reactive component model. They optimize for different balances of ergonomics, ecosystem breadth, and runtime strategy.',
  },
  {
    title: 'Vue versus Nuxt',
    body: 'Vue is the UI framework underneath, while Nuxt is the application framework layer around Vue. Choosing between them is usually about whether the project needs only the component model or also needs routing, server rendering, data delivery, and deployment structure from the start.',
  },
]

const failureModes = [
  {
    title: 'Letting components grow too broad',
    body: 'Single-file components are convenient, but they can become oversized if teams keep adding logic, template branches, styles, and side effects into one place. Component locality helps only when the component still represents one clear responsibility.',
  },
  {
    title: 'Using watchers where computed state would be clearer',
    body: 'Watchers can solve real problems, but they often become accidental complexity when used to mirror or transform state that should have been modeled as computed data. This makes update paths harder to follow.',
  },
  {
    title: 'Creating too many loosely defined composables',
    body: 'The Composition API makes reuse easy, but not every repeated line deserves a composable. Poorly scoped composables can hide dependencies, leak state responsibilities, and make the codebase feel more abstract than the problem requires.',
  },
  {
    title: 'Confusing local state, store state, and route state',
    body: 'Vue applications often use several reactive layers at once. Problems arise when teams do not decide clearly whether a value belongs in a component, a composable, a store, or the route. The result is overlapping state and hard-to-debug synchronization issues.',
  },
  {
    title: 'Assuming framework ergonomics replace architectural planning',
    body: 'Vue can feel pleasant enough that teams underestimate the need for structure. The application still needs intentional design around routing, stores, async data, and domain boundaries if it is going to remain maintainable.',
  },
]

const studyChecklist = [
  'Understand Vue as a reactive component framework, not only as template syntax.',
  'Learn the difference between props, emits, local refs, computed values, watchers, composables, and stores.',
  'Keep components and composables focused so reactive state remains easy to trace.',
  'Use watchers intentionally and prefer derived state when that models the problem more clearly.',
  'Choose state boundaries deliberately across components, stores, and route-level concerns.',
  'Remember that Nuxt adds a separate application architecture layer on top of Vue when the project needs it.',
]

const examples = [
  {
    id: 'vue98-example-component',
    title: 'Example: Reactive component state',
    area: 'State',
    intro:
      'A Vue component can declare local reactive state and render template output directly from it.',
    whyFit:
      'This captures the most basic Vue idea: the template reflects reactive data rather than manual DOM updates.',
    code: `<script setup>
import { ref } from 'vue'

const count = ref(0)
</script>

<template>
  <button @click="count += 1">Count: {{ count }}</button>
</template>`,
    takeaway:
      'Vue stays easiest to reason about when local state remains local and the template clearly reflects that state.',
  },
  {
    id: 'vue98-example-computed',
    title: 'Example: Computed derived state',
    area: 'Derived Data',
    intro:
      'Computed values let a component derive view-ready data from reactive sources without duplicating that state manually.',
    whyFit: 'This shows how Vue distinguishes source state from derived state in a readable way.',
    code: `<script setup>
import { computed, ref } from 'vue'

const count = ref(3)
const doubled = computed(() => count.value * 2)
</script>

<template>
  <p>{{ count }} doubled is {{ doubled }}</p>
</template>`,
    takeaway:
      'Computed values are often clearer than watchers when the goal is to derive one value from another predictably.',
  },
  {
    id: 'vue98-example-props',
    title: 'Example: Props and emits',
    area: 'Component Contracts',
    intro:
      'A child component receives input through props and communicates back through emitted events.',
    whyFit:
      'This reflects the standard Vue contract between reusable components and their consumers.',
    code: `<script setup>
defineProps<{ label: string }>()
const emit = defineEmits<{ save: [] }>()
</script>

<template>
  <button @click="emit('save')">{{ label }}</button>
</template>`,
    takeaway:
      'Clear prop and event contracts keep component relationships explicit even in large trees.',
  },
  {
    id: 'vue98-example-composable',
    title: 'Example: Reusable composable',
    area: 'Reusable Logic',
    intro:
      'A composable can package reactive behavior into a reusable function that multiple components can consume.',
    whyFit:
      'This demonstrates how modern Vue shares stateful logic without forcing everything into one component or store.',
    code: `import { computed, ref } from 'vue'

export function useCounter() {
  const count = ref(0)
  const doubled = computed(() => count.value * 2)

  return { count, doubled }
}`,
    takeaway:
      'Composables are strongest when they encapsulate one real behavior pattern with a clear interface.',
  },
  {
    id: 'vue98-example-store',
    title: 'Example: Pinia store',
    area: 'Shared State',
    intro:
      'A store can hold shared application state when the same data or actions must coordinate across multiple routes or components.',
    whyFit:
      'This shows how Vue applications often move from local reactivity to store-managed shared state as they grow.',
    code: `import { defineStore } from 'pinia'

export const useCartStore = defineStore('cart', {
  state: () => ({ items: [] as string[] }),
  actions: {
    add(item: string) {
      this.items.push(item)
    },
  },
})`,
    takeaway:
      'Stores are useful for shared state, but they should represent real shared ownership rather than becoming the default home for every value.',
  },
]

const glossary = [
  {
    term: 'Vue.js',
    definition: 'A frontend framework for building reactive, component-driven user interfaces.',
  },
  {
    term: 'Single-file component',
    definition:
      'A Vue component file that commonly colocates template, script, and style sections.',
  },
  {
    term: 'ref',
    definition: 'A Vue reactive primitive commonly used to store and update a value over time.',
  },
  {
    term: 'computed',
    definition: 'A Vue mechanism for deriving reactive values from other reactive sources.',
  },
  {
    term: 'watch',
    definition:
      'A Vue tool for observing reactive values and running side effects when they change.',
  },
  {
    term: 'Composition API',
    definition:
      'A Vue API style centered on refs, computed values, watchers, and composables for organizing logic.',
  },
  {
    term: 'Composable',
    definition: 'A reusable Vue function that encapsulates reactive state or behavior.',
  },
  {
    term: 'Pinia',
    definition: 'The official state management library commonly used in modern Vue applications.',
  },
  {
    term: 'Directive',
    definition:
      'A special Vue template syntax such as v-if, v-for, or v-model that attaches framework behavior to markup.',
  },
  {
    term: 'Nuxt',
    definition:
      'The application framework layer commonly used around Vue for routing, server rendering, and hybrid web delivery.',
  },
]

const tabs: Array<{ id: TabId; label: string }> = [
  { id: 'big-picture', label: 'The Big Picture' },
  { id: 'core-concepts', label: 'Core Concepts' },
  { id: 'examples', label: 'Examples' },
  { id: 'glossary', label: 'Glossary' },
]

const sectionLinks: Record<TabId, Array<{ id: string; label: string }>> = {
  'big-picture': [
    { id: 'vue98-overview', label: 'Overview' },
    { id: 'vue98-why', label: 'Why It Matters' },
    { id: 'vue98-history', label: 'Historical Context' },
    { id: 'vue98-themes', label: 'Big Picture Themes' },
    { id: 'vue98-takeaways', label: 'Key Takeaways' },
  ],
  'core-concepts': [
    { id: 'vue98-signals', label: 'Topic Signals' },
    { id: 'vue98-foundations', label: 'Foundations' },
    { id: 'vue98-features', label: 'Framework Features' },
    { id: 'vue98-runtime', label: 'Runtime and Operations' },
    { id: 'vue98-uses', label: 'Ecosystem Uses' },
    { id: 'vue98-compare', label: 'Compare and Contrast' },
    { id: 'vue98-failures', label: 'Failure Modes' },
    { id: 'vue98-checklist', label: 'Study Checklist' },
  ],
  examples: examples.map((example) => ({ id: example.id, label: example.title })),
  glossary: [{ id: 'vue98-glossary', label: 'Terms' }],
}

export default function VuePage(): JSX.Element {
  const { activeTab, setActiveTab, handleMinimize } = useTopicTabs({
    tabs,
    pageTitle: 'Vue.js (Frontend)',
    defaultTab: 'big-picture',
  })

  return (
    <TopicPageShell
      title="Vue.js (Frontend)"
      tabs={tabs}
      activeTab={activeTab}
      onTabChange={setActiveTab}
      tocLinks={sectionLinks[activeTab]}
      onMinimize={handleMinimize}
    >
      <h1 className="bin98-doc-title">Vue.js (Frontend)</h1>
      <p className="vue98-intro">
        This page is a frontend-focused overview of Vue.js as a reactive component framework. It
        explains templates, refs, computed values, watchers, composables, stores, ecosystem
        tradeoffs, and the design discipline required to keep a Vue codebase understandable as it
        grows.
      </p>

      {activeTab === 'big-picture' && (
        <>
          <section id="vue98-overview" className="bin98-section">
            <h2 className="bin98-heading">Overview</h2>
            {overviewSections.map((section) => (
              <div key={section.title}>
                <h3 className="bin98-subheading">{section.title}</h3>
                <p>{section.body}</p>
              </div>
            ))}
          </section>

          <hr className="bin98-divider" />

          <section id="vue98-why" className="bin98-section">
            <h2 className="bin98-heading">Why It Matters</h2>
            <ul>
              {whyItMatters.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </section>

          <hr className="bin98-divider" />

          <section id="vue98-history" className="bin98-section">
            <h2 className="bin98-heading">Historical Context</h2>
            {historicalContext.map((item) => (
              <div key={item.title}>
                <h3 className="bin98-subheading">{item.title}</h3>
                <p>{item.detail}</p>
              </div>
            ))}
          </section>

          <hr className="bin98-divider" />

          <section id="vue98-themes" className="bin98-section">
            <h2 className="bin98-heading">Big Picture Themes</h2>
            {bigPictureThemes.map((item) => (
              <div key={item.title}>
                <h3 className="bin98-subheading">{item.title}</h3>
                <p>{item.body}</p>
              </div>
            ))}
          </section>

          <hr className="bin98-divider" />

          <section id="vue98-takeaways" className="bin98-section">
            <h2 className="bin98-heading">Key Takeaways</h2>
            <ul>
              {keyTakeaways.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </section>
        </>
      )}

      {activeTab === 'core-concepts' && (
        <>
          <section id="vue98-signals" className="bin98-section">
            <h2 className="bin98-heading">Topic Signals</h2>
            {topicSignals.map((item) => (
              <div key={item.title}>
                <h3 className="bin98-subheading">{item.title}</h3>
                <p>{item.body}</p>
              </div>
            ))}
          </section>

          <section id="vue98-foundations" className="bin98-section">
            <h2 className="bin98-heading">Foundations</h2>
            {coreFoundations.map((item) => (
              <div key={item.title}>
                <h3 className="bin98-subheading">{item.title}</h3>
                <p>{item.body}</p>
              </div>
            ))}
          </section>

          <section id="vue98-features" className="bin98-section">
            <h2 className="bin98-heading">Framework Features</h2>
            {frameworkFeatures.map((item) => (
              <div key={item.title}>
                <h3 className="bin98-subheading">{item.title}</h3>
                <p>{item.body}</p>
              </div>
            ))}
          </section>

          <section id="vue98-runtime" className="bin98-section">
            <h2 className="bin98-heading">Runtime and Operations</h2>
            {runtimeAndOperations.map((item) => (
              <div key={item.title}>
                <h3 className="bin98-subheading">{item.title}</h3>
                <p>{item.body}</p>
              </div>
            ))}
          </section>

          <section id="vue98-uses" className="bin98-section">
            <h2 className="bin98-heading">Ecosystem Uses</h2>
            {ecosystemUses.map((item) => (
              <div key={item.title}>
                <h3 className="bin98-subheading">{item.title}</h3>
                <p>{item.body}</p>
              </div>
            ))}
          </section>

          <section id="vue98-compare" className="bin98-section">
            <h2 className="bin98-heading">Compare and Contrast</h2>
            {comparisons.map((item) => (
              <div key={item.title}>
                <h3 className="bin98-subheading">{item.title}</h3>
                <p>{item.body}</p>
              </div>
            ))}
          </section>

          <section id="vue98-failures" className="bin98-section">
            <h2 className="bin98-heading">Failure Modes</h2>
            {failureModes.map((item) => (
              <div key={item.title}>
                <h3 className="bin98-subheading">{item.title}</h3>
                <p>{item.body}</p>
              </div>
            ))}
          </section>

          <section id="vue98-checklist" className="bin98-section">
            <h2 className="bin98-heading">Study Checklist</h2>
            <ul>
              {studyChecklist.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </section>
        </>
      )}

      {activeTab === 'examples' && (
        <>
          {examples.map((example) => (
            <section key={example.id} id={example.id} className="bin98-section">
              <h2 className="bin98-heading">{example.title}</h2>
              <p>
                <strong>Area:</strong> {example.area}
              </p>
              <p>{example.intro}</p>
              <p>
                <strong>Why this example fits:</strong> {example.whyFit}
              </p>
              <div className="bin98-codebox">
                <code>{example.code}</code>
              </div>
              <p>
                <strong>Takeaway:</strong> {example.takeaway}
              </p>
            </section>
          ))}
        </>
      )}

      {activeTab === 'glossary' && (
        <section id="vue98-glossary" className="bin98-section">
          <h2 className="bin98-heading">Glossary</h2>
          {glossary.map((entry) => (
            <p key={entry.term}>
              <strong>{entry.term}:</strong> {entry.definition}
            </p>
          ))}
        </section>
      )}
    </TopicPageShell>
  )
}
