// src/features/dsa/routes/DSA/0. Languages & Ecosystems/Frameworks/Frontend/Next.js/index.tsx
import { Fragment } from 'react'

import TopicPageShell from '@/features/dsa/components/TopicPageShell'
import { useTopicTabs } from '@/features/dsa/hooks/useTopicTabs'

import type { JSX } from 'react'

type DocSection = {
  id: string
  title: string
  paragraphs: readonly string[]
}

type ExampleSnippet = {
  label: string
  code: string
}

type ExampleSection = {
  id: string
  title: string
  description: string
  snippets: readonly ExampleSnippet[]
  takeaway: string
}

type GlossaryTerm = {
  term: string
  definition: string
}

type TabId = 'big-picture' | 'core-concepts' | 'examples' | 'glossary'

const bigPictureSections: readonly DocSection[] = [
  {
    id: 'bp-overview',
    title: 'Overview',
    paragraphs: [
      'Next.js is a React framework for building full-stack web applications. It provides file-system routing, server and client rendering strategies, route handlers, layouts, data-fetching patterns, middleware, deployment-aware optimizations, and a coordinated application model around React.',
      'In practice, Next.js is used for marketing sites, content platforms, e-commerce fronts, dashboards, SaaS products, internal tools, documentation systems, and large production web applications that need more than plain React components.',
      'This help-style version expands the original placeholder into a fuller reference covering App Router mental model, server and client components, route handlers, caching, rendering, navigation, use cases, tradeoffs, examples, and glossary terms.',
    ],
  },
  {
    id: 'bp-why-next',
    title: 'Why Teams Reach For Next.js',
    paragraphs: [
      'Next.js matters because it turns React from a UI library into a broad application platform. Instead of leaving routing, rendering mode, request handling, bundling, image optimization, and deployment patterns as separate decisions, it offers one framework story for many of them.',
      'The practical appeal is consistency. Teams can adopt a route-aware, server-capable React stack with built-in conventions rather than stitching together a large set of packages and internal rules for every project.',
    ],
  },
  {
    id: 'bp-what-it-optimizes',
    title: 'What Next.js Optimizes For',
    paragraphs: [
      'Next.js optimizes for React application development with strong production-focused defaults. It tries to make routing, rendering, caching, navigation, bundling, and server integration feel like one framework problem instead of many disconnected infrastructure problems.',
      'It also optimizes for deployment and runtime flexibility. Different routes and components can participate in different rendering and caching strategies, and the framework is built with server execution, streaming, and route-aware optimization in mind.',
    ],
  },
  {
    id: 'bp-react-relationship',
    title: 'Relationship to React',
    paragraphs: [
      'Next.js is built on React, but it is not just React with a router. The framework defines how React is structured into routes, layouts, server and client boundaries, request handlers, and deployment behavior.',
      'This distinction matters because a Next.js codebase often feels substantially different from plain React. The component model is still React, but much of the architecture is decided by the framework.',
    ],
  },
  {
    id: 'bp-app-router',
    title: 'Why the App Router Matters',
    paragraphs: [
      'Current Next.js guidance centers on the App Router. It is the newer router model that uses React Server Components, layouts, route segments, loading states, error boundaries, route handlers, and server-side mutation patterns as first-class architecture concepts.',
      'This changes how teams think about React applications. Instead of a mostly client-driven route tree with optional SSR around it, the framework treats server rendering and route-segment boundaries as core parts of normal app structure.',
    ],
  },
  {
    id: 'bp-pages-router',
    title: 'Pages Router Still Exists',
    paragraphs: [
      'Next.js still supports the older Pages Router, and it remains relevant in existing codebases. However, the App Router is the main direction for newer framework features and for the current mental model discussed in official documentation.',
      'That means teams maintaining older projects may need to understand both models. The architectural center of new greenfield work is usually the App Router, while legacy products may still use Pages Router conventions.',
    ],
  },
  {
    id: 'bp-where-it-fits',
    title: 'Where Next.js Fits Well',
    paragraphs: [
      'Next.js is a strong fit for full-stack React products that need route-level structure, SSR or hybrid rendering, SEO-sensitive pages, React Server Component workflows, and a deployment-aware platform story.',
      'It is also a common organizational default when teams want a mainstream React framework with strong ecosystem gravity and a broad set of built-in capabilities.',
    ],
  },
  {
    id: 'bp-common-misreadings',
    title: 'Common Misreadings',
    paragraphs: [
      'A common mistake is to treat Next.js as if it were just React plus file-based routing. That misses the importance of server and client component boundaries, cache behavior, route handlers, and rendering policy.',
      'Another mistake is to discuss the framework without naming which router model is being used. Many historical blog posts and code examples are Pages Router based, while many modern patterns assume the App Router.',
    ],
  },
  {
    id: 'bp-takeaways',
    title: 'Quick Takeaways',
    paragraphs: [
      'Next.js centers on React plus a full application framework layer for routing, rendering, server integration, and deployment-aware optimization.',
      'Its main strengths are integrated architecture, large ecosystem gravity, strong React alignment, and flexible rendering and caching options.',
      'Its main tradeoffs are framework complexity, the need to understand server and client boundaries carefully, and the fact that framework behavior can be more sophisticated than plain React teams initially expect.',
    ],
  },
] as const

const coreConceptSections: readonly DocSection[] = [
  {
    id: 'core-mental-model',
    title: 'Mental Model',
    paragraphs: [
      'Next.js asks developers to think in terms of routes, layouts, and server-aware rendering boundaries rather than only in terms of client-side components. The route tree becomes a major architectural tool, and server work is not an afterthought layered on top of a purely client app.',
      'This is especially true in the App Router. Pages and layouts are server-first by default, and interactivity is layered in with explicit client component boundaries where needed.',
    ],
  },
  {
    id: 'core-app-router',
    title: 'App Router',
    paragraphs: [
      'The App Router is the newer file-system router in Next.js and the main framework direction in the current docs. It uses route segments, layouts, React Server Components, route handlers, loading states, and error boundaries as core building blocks.',
      'This gives the framework a route-centered architecture where navigation, rendering, and data loading are shaped by the file structure inside the `app/` directory.',
    ],
  },
  {
    id: 'core-project-structure',
    title: 'Project Structure and File Conventions',
    paragraphs: [
      'Next.js uses file conventions such as `app/`, `page.tsx`, `layout.tsx`, `loading.tsx`, `error.tsx`, and `route.ts` to define route behavior and UI structure. The framework reads meaning from those files rather than asking teams to register every behavior manually.',
      'This convention-first design reduces setup and helps teams navigate codebases more quickly, but it also means developers must learn what each special file means in the framework lifecycle.',
    ],
  },
  {
    id: 'core-layouts',
    title: 'Layouts and Route Segments',
    paragraphs: [
      'Layouts are a major part of the App Router. Shared UI shells can persist across navigation while only the changed route segments rerender. This helps route hierarchy shape both user experience and application structure.',
      'The architectural effect is significant: a route tree becomes a composition model for shared shells, nested content, loading states, and cache reuse rather than only a URL mapping table.',
    ],
  },
  {
    id: 'core-server-client',
    title: 'Server and Client Components',
    paragraphs: [
      'In the App Router, pages and layouts are Server Components by default. They can render on the server, fetch data directly, participate in streaming, and avoid sending unnecessary component logic to the client.',
      'When a component needs state, event handlers, lifecycle logic, or browser APIs, it must become a Client Component through the `use client` directive. That boundary is one of the most important architectural decisions in modern Next.js.',
    ],
  },
  {
    id: 'core-boundaries',
    title: 'Why the Boundary Matters',
    paragraphs: [
      'The server and client boundary is not just a code-style preference. It determines bundle size, execution environment, data access patterns, and how much JavaScript the browser needs to download and run.',
      'Good Next.js architecture usually keeps as much as practical on the server while moving only truly interactive UI logic into client components.',
    ],
  },
  {
    id: 'core-data-fetching',
    title: 'Data Fetching in the App Router',
    paragraphs: [
      'A major shift in Next.js is that data can be fetched directly in Server Components using normal async patterns. This keeps server-owned data loading close to the route or component that needs it and can reduce the amount of client fetch orchestration required.',
      'The framework also layers caching and revalidation behavior on top of data fetching, so teams need to understand not only how to fetch data, but how that data is cached and refreshed.',
    ],
  },
  {
    id: 'core-caching',
    title: 'Caching Model',
    paragraphs: [
      'Next.js has a sophisticated caching model involving route output, fetched data, and client-side router behavior. The practical implication is that route performance and freshness depend on understanding what is cached, where it is cached, and how revalidation happens.',
      "This is one of the framework's biggest strengths and one of its main sources of confusion. Teams that ignore caching semantics often misread why a route is static, dynamic, reused, or refreshed.",
    ],
  },
  {
    id: 'core-navigation',
    title: 'Navigation, Prefetching, and Partial Rendering',
    paragraphs: [
      'Next.js uses built-in navigation with route-aware prefetching and partial rendering behavior. Shared layouts can remain mounted, and navigation often reuses cached route information to make transitions feel faster and more app-like.',
      "This means navigation is not only a router concern. It is directly tied to the framework's route segmentation and cache behavior.",
    ],
  },
  {
    id: 'core-loading-error',
    title: 'Loading and Error Boundaries',
    paragraphs: [
      'App Router conventions such as `loading.tsx` and `error.tsx` give routes explicit places for pending and failure states. This helps teams keep fallback UI and error handling aligned with route structure instead of scattering them through many components.',
      'The practical benefit is clarity. A route segment can define how it loads and how it fails as part of its normal module structure.',
    ],
  },
] as const

const coreConceptSectionsContinued: readonly DocSection[] = [
  {
    id: 'core-route-handlers',
    title: 'Route Handlers',
    paragraphs: [
      'Route Handlers in the App Router allow developers to define request handlers with Web Request and Response APIs inside the `app/` directory. They are the modern framework answer for custom backend endpoints associated with a route tree.',
      'This gives Next.js a native server endpoint story inside the application framework instead of forcing every project to stand up a separate API layer for simple integrated server logic.',
    ],
  },
  {
    id: 'core-server-actions',
    title: 'Server Functions and Mutations',
    paragraphs: [
      'Modern Next.js also uses server-side function patterns for mutations and server-executed logic. This reflects the broader direction of keeping more application behavior close to the server while letting client components trigger server work where needed.',
      'The key engineering question is not merely whether a mutation works, but whether the team has chosen the right boundary between server-owned logic and client-owned interactivity.',
    ],
  },
  {
    id: 'core-rendering-modes',
    title: 'Static, Dynamic, and Streaming Rendering',
    paragraphs: [
      'Next.js supports static generation, dynamic rendering, streaming, and mixed route behavior depending on what the route needs. Different data access patterns and configuration choices can move a route toward static or request-time rendering.',
      'That flexibility is powerful because a marketing page and a personalized dashboard do not need the same runtime policy. It also means teams should be deliberate about route behavior instead of assuming every page is rendered the same way.',
    ],
  },
  {
    id: 'core-middleware',
    title: 'Middleware and Request Flow',
    paragraphs: [
      'Next.js includes middleware capabilities that allow request-time logic such as redirects, rewrites, or authentication-related checks to run before a route resolves. This lets some cross-cutting behavior live near the edge of the request lifecycle.',
      'Teams should still use middleware judiciously. It is powerful, but it is best reserved for concerns that truly belong at the request boundary rather than in component code.',
    ],
  },
  {
    id: 'core-assets-optimization',
    title: 'Built-In Optimization Features',
    paragraphs: [
      'Next.js includes built-in features such as the `Link` component, image optimization, font tooling, code splitting, and route-aware bundling behavior. These are part of why the framework is often chosen for production-facing web apps rather than only for component rendering.',
      'The important point is that the framework tries to turn common web performance work into platform defaults, though teams still need to understand the tradeoffs and operational impact of those defaults.',
    ],
  },
  {
    id: 'core-typescript',
    title: 'TypeScript and Tooling',
    paragraphs: [
      'Next.js works closely with TypeScript, modern bundling, and React-aware linting and build workflows. In practice, many teams experience the framework as a coordinated toolchain as much as a runtime.',
      'That coordination is useful, but it also means framework upgrades and feature adoption can affect many layers of the project at once, including routing, build output, and runtime behavior.',
    ],
  },
  {
    id: 'core-ecosystem',
    title: 'Ecosystem and Platform Gravity',
    paragraphs: [
      'Next.js sits at the center of a large part of the React framework ecosystem. Many tutorials, templates, deployment workflows, hosting integrations, and adjacent tools assume or directly target Next.js.',
      'That ecosystem gravity is a major strength for hiring, support, and package compatibility. It can also create pressure to use the framework even when a narrower or simpler architecture might be sufficient.',
    ],
  },
  {
    id: 'core-pages-router',
    title: 'Pages Router in Existing Codebases',
    paragraphs: [
      'The Pages Router still matters because many production applications were built with it and continue to run successfully. Concepts such as `pages/`, `getServerSideProps`, and API routes remain relevant in maintenance and migration work.',
      'The important practical point is to avoid mixing mental models accidentally. App Router and Pages Router codebases often solve similar problems in meaningfully different ways.',
    ],
  },
  {
    id: 'core-use-cases',
    title: 'Use Cases',
    paragraphs: [
      'Next.js is frequently used for content-rich sites, e-commerce fronts, SaaS apps, admin panels, documentation, dashboards, and products that need a React-first framework with SSR or hybrid rendering support.',
      'It is also a common organizational default when teams want a broad React platform with strong deployment and tooling support rather than hand-assembling the entire app stack.',
    ],
  },
  {
    id: 'core-tradeoffs',
    title: 'Tradeoffs',
    paragraphs: [
      'Next.js offers a lot, but it asks teams to understand a relatively large framework surface. Routing conventions, server and client boundaries, cache semantics, route handlers, and rendering modes create real conceptual weight compared with plain React.',
      'Another tradeoff is that framework defaults can interact in subtle ways. Developers may need to understand why data is cached, why a route became dynamic, or why a component must be client-only, rather than assuming every issue is just ordinary React behavior.',
    ],
  },
  {
    id: 'core-compare',
    title: 'Compare and Contrast References',
    paragraphs: [
      'Next.js is commonly compared with plain React for framework integration versus library flexibility, with Remix for broad platform scope versus a more web-request-centered full-stack model, and with Nuxt for how React and Vue ecosystems approach integrated application frameworks.',
      'These comparisons help position Next.js correctly: it is the mainstream full-stack React framework choice for many teams, not just a small routing addon on top of React.',
    ],
  },
] as const
const coreConceptSectionsMerged: readonly DocSection[] = [
  ...coreConceptSections,
  ...coreConceptSectionsContinued,
]

const examples: readonly ExampleSection[] = [
  {
    id: 'examples-page',
    title: 'Server Component Page',
    description:
      'In the App Router, a page can be a Server Component by default and fetch data directly on the server without adding a client-side fetching layer first.',
    snippets: [
      {
        label: 'app/products/page.tsx',
        code: `async function getProducts() {
  const response = await fetch('https://example.com/api/products')
  return response.json()
}

export default async function ProductsPage() {
  const products = await getProducts()

  return (
    <ul>
      {products.map((product: { id: string; name: string }) => (
        <li key={product.id}>{product.name}</li>
      ))}
    </ul>
  )
}`,
      },
    ],
    takeaway:
      'A major Next.js mental shift is that many route-level data needs can stay on the server by default instead of being orchestrated through client hooks first.',
  },
  {
    id: 'examples-client',
    title: 'Client Component Boundary',
    description:
      'When interactivity, state, or browser APIs are needed, a component becomes client-side through the `use client` directive.',
    snippets: [
      {
        label: 'app/components/counter.tsx',
        code: `'use client'


export default function Counter() {
  const [count, setCount] = useState(0)

  return (
    <button onClick={() => setCount((value) => value + 1)}>
      Count: {count}
    </button>
  )
}`,
      },
    ],
    takeaway:
      'Client components are opt-in in the App Router. The boundary should be drawn intentionally because it changes execution environment and bundle cost.',
  },
  {
    id: 'examples-layout',
    title: 'Layout and Nested Route Shape',
    description:
      "Layouts are persistent route shells in the App Router. They are one of the framework's main architectural tools for shared structure and partial rendering.",
    snippets: [
      {
        label: 'app/dashboard/layout.tsx',
        code: `export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main>
      <aside>Dashboard navigation</aside>
      <section>{children}</section>
    </main>
  )
}`,
      },
      {
        label: 'app/dashboard/page.tsx',
        code: `export default function DashboardPage() {
  return <h1>Dashboard</h1>
}`,
      },
    ],
    takeaway:
      'In Next.js, route hierarchy is not only about URLs. It also defines persistent layout structure and what parts of the UI can be reused across navigation.',
  },
  {
    id: 'examples-route-handler',
    title: 'Route Handler Example',
    description:
      'Route Handlers provide an in-framework server endpoint model using Web Request and Response APIs inside the App Router.',
    snippets: [
      {
        label: 'app/api/products/route.ts',
        code: `export async function GET() {
  return Response.json([
    { id: '1', name: 'Keyboard' },
    { id: '2', name: 'Monitor' },
  ])
}`,
      },
    ],
    takeaway:
      'This keeps simple backend endpoints close to the app without requiring a separate API project for every server interaction.',
  },
  {
    id: 'examples-architecture',
    title: 'Architecture Snapshot',
    description:
      'A typical modern Next.js application uses the App Router as the organizing center for rendering, routing, server work, and navigation behavior.',
    snippets: [
      {
        label: 'Common Stack',
        code: `React for component authoring
App Router for route segments, layouts, loading states, and route handlers
Server Components by default for route-level rendering and data access
Client Components only where interactivity or browser APIs are required
Framework-managed caching, prefetching, and route-aware navigation`,
      },
    ],
    takeaway:
      'Next.js works best when the team treats it as a full framework with explicit server and client boundaries, not merely as React with nicer routing.',
  },
] as const

const glossaryTerms: readonly GlossaryTerm[] = [
  {
    term: 'Next.js',
    definition:
      'A React framework for building full-stack web applications with routing, rendering, server integration, and deployment-aware optimization.',
  },
  {
    term: 'App Router',
    definition:
      'The newer Next.js router model built around route segments, layouts, React Server Components, and file conventions in the `app/` directory.',
  },
  {
    term: 'Pages Router',
    definition:
      'The older Next.js router model based on the `pages/` directory, still supported and common in existing production codebases.',
  },
  {
    term: 'Server Component',
    definition:
      'A React component rendered on the server by default in the Next.js App Router, useful for server-side data access and reducing client bundle work.',
  },
  {
    term: 'Client Component',
    definition:
      'A React component marked with `use client` so it can use state, effects, event handlers, and browser APIs.',
  },
  {
    term: 'Route segment',
    definition:
      'A portion of the route tree in the App Router that can define layouts, pages, loading states, and related behavior.',
  },
  {
    term: 'Layout',
    definition:
      'A shared route shell that can persist across navigation and wrap nested route content.',
  },
  {
    term: 'Route Handler',
    definition:
      'A request handler inside the App Router, typically defined in `route.ts`, that uses Web Request and Response APIs.',
  },
  {
    term: 'Streaming',
    definition:
      'A rendering strategy where the server sends parts of the response as they become ready instead of waiting for the entire page to finish.',
  },
  {
    term: 'Prefetching',
    definition:
      'The framework behavior of loading route information ahead of navigation to make transitions feel faster.',
  },
  {
    term: 'Router cache',
    definition:
      'A client-side cache used by Next.js to store route-related payloads and improve navigation behavior.',
  },
  {
    term: 'Revalidation',
    definition:
      'The process of refreshing cached route or data output so the application reflects newer server state.',
  },
  {
    term: 'Middleware',
    definition:
      'Request-bound logic that runs before a route resolves, often used for redirects, rewrites, or access control checks.',
  },
  {
    term: 'Loading UI',
    definition:
      'A route-segment fallback state, often defined through `loading.tsx`, shown while server work is still in progress.',
  },
  {
    term: 'Error boundary',
    definition:
      'A route-segment error surface, often defined through `error.tsx`, used when rendering or data work fails.',
  },
  {
    term: 'Route segment config',
    definition:
      'Per-route configuration that influences rendering or runtime behavior in the App Router.',
  },
] as const

const tabs: Array<{ id: TabId; label: string }> = [
  { id: 'big-picture', label: 'The Big Picture' },
  { id: 'core-concepts', label: 'Core Concepts' },
  { id: 'examples', label: 'Examples' },
  { id: 'glossary', label: 'Glossary' },
]

const sectionLinks: Record<TabId, Array<{ id: string; label: string }>> = {
  'big-picture': bigPictureSections.map((section) => ({ id: section.id, label: section.title })),
  'core-concepts': coreConceptSectionsMerged.map((section) => ({
    id: section.id,
    label: section.title,
  })),
  examples: examples.map((section) => ({ id: section.id, label: section.title })),
  glossary: [{ id: 'glossary-terms', label: 'Terms' }],
}

export default function Counter(): JSX.Element {
  const { activeTab, setActiveTab, handleMinimize } = useTopicTabs({
    tabs,
    pageTitle: 'Next.js',
    defaultTab: 'big-picture',
  })

  return (
    <TopicPageShell
      title="Next.js"
      tabs={tabs}
      activeTab={activeTab}
      onTabChange={setActiveTab}
      tocLinks={sectionLinks[activeTab]}
      onMinimize={handleMinimize}
    >
      <h1 className="bin98-doc-title">Next.js</h1>
      <p className="next-js-help-doc-subtitle">
        Manual-style reference covering overview, App Router, server and client components, route
        handlers, caching, rendering strategies, tradeoffs, and practical examples.
      </p>

      {activeTab === 'big-picture' &&
        bigPictureSections.map((section, index) => (
          <Fragment key={section.id}>
            <section id={section.id} className="bin98-section">
              <h2 className="bin98-heading">{section.title}</h2>
              {section.paragraphs.map((paragraph) => (
                <p key={paragraph}>{paragraph}</p>
              ))}
            </section>
            {index < bigPictureSections.length - 1 && <hr className="bin98-divider" />}
          </Fragment>
        ))}

      {activeTab === 'core-concepts' &&
        coreConceptSectionsMerged.map((section) => (
          <section key={section.id} id={section.id} className="bin98-section">
            <h2 className="bin98-heading">{section.title}</h2>
            {section.paragraphs.map((paragraph) => (
              <p key={paragraph}>{paragraph}</p>
            ))}
          </section>
        ))}

      {activeTab === 'examples' &&
        examples.map((example) => (
          <section key={example.id} id={example.id} className="bin98-section">
            <h2 className="bin98-heading">{example.title}</h2>
            <p>{example.description}</p>
            {example.snippets.map((snippet) => (
              <Fragment key={`${example.id}-${snippet.label}`}>
                <h3 className="bin98-subheading">{snippet.label}</h3>
                <div className="bin98-codebox">
                  <code>{snippet.code}</code>
                </div>
              </Fragment>
            ))}
            <p>
              <strong>Takeaway:</strong> {example.takeaway}
            </p>
          </section>
        ))}

      {activeTab === 'glossary' && (
        <section id="glossary-terms" className="bin98-section">
          <h2 className="bin98-heading">Glossary</h2>
          {glossaryTerms.map((item) => (
            <p key={item.term}>
              <strong>{item.term}:</strong> {item.definition}
            </p>
          ))}
        </section>
      )}
    </TopicPageShell>
  )
}

// src/features/dsa/routes/DSA/0. Programming Languages/Languages/Frameworks/Frontend/Vue.js/index.tsx
import { Fragment, useEffect, useState } from 'react'
import { Link, useLocation, useNavigate, useSearchParams } from 'react-router-dom'

import type { JSX } from 'react'

type DocSection = {
  id: string
  title: string
  paragraphs: readonly string[]
}

type ExampleSnippet = {
  label: string
  code: string
}

type ExampleSection = {
  id: string
  title: string
  description: string
  snippets: readonly ExampleSnippet[]
  takeaway: string
}

type GlossaryTerm = {
  term: string
  definition: string
}

type TabId = 'big-picture' | 'core-concepts' | 'examples' | 'glossary'

const MINIMIZED_HELP_TASKS_KEY = 'win96:minimized-help-tasks'

const bigPictureSections: readonly DocSection[] = [
  {
    id: 'bp-overview',
    title: 'Overview',
    paragraphs: [
      'Vue.js is a progressive frontend framework for building interactive user interfaces. It focuses on declarative rendering, component composition, and a built-in reactivity model that lets UI update when application state changes.',
      'The framework is often adopted for single-page applications, dashboards, content-rich frontends, and incrementally enhanced interfaces. Teams frequently choose it when they want a cohesive developer experience without moving to a heavier all-in platform.',
      'The original page scope was placeholder content for Vue.js. This help-style version keeps that scope while organizing the material into overview, key ideas, core syntax, APIs, ecosystem, architecture, examples, use cases, tradeoffs, and reference-oriented terminology.',
    ],
  },
  {
    id: 'bp-why',
    title: 'Why Teams Reach For Vue',
    paragraphs: [
      'Vue offers a relatively approachable path into component-based frontend development. Templates stay readable, Single-File Components keep related concerns together, and the reactivity system gives developers explicit primitives for state and derived values.',
      'The practical appeal is not only syntax. Vue also provides official or closely aligned solutions for routing, state management, dev tooling, and server-rendering-related workflows, which can reduce architecture drift across projects.',
    ],
  },
  {
    id: 'bp-scope',
    title: 'What This Page Covers',
    paragraphs: [
      'This page keeps all of the original planned concepts: overview and key ideas, core syntax, APIs, ecosystem, architecture, use cases, tradeoffs, and compare-and-contrast references that help place Vue among other frontend options.',
      'The goal is a text-first reference page in the style of a classic desktop help document. It is meant for scanning, review, and returning to individual sections through the page-local table of contents and tab state.',
    ],
  },
  {
    id: 'bp-fit',
    title: 'Where Vue Fits Well',
    paragraphs: [
      'Vue is a strong fit when a team wants a modern reactive UI framework with strong defaults, a gentle learning curve, and a clear path from simple components to larger applications. It is also commonly chosen for products that value fast onboarding and consistent component authoring patterns.',
      'Compared with more library-first stacks, Vue usually gives teams more structure out of the box. Compared with heavier frameworks, it often feels lighter and easier to introduce incrementally.',
    ],
  },
  {
    id: 'bp-takeaways',
    title: 'Quick Takeaways',
    paragraphs: [
      'Vue centers on components, templates, and reactive state.',
      'Its main strengths are approachability, cohesive tooling, and ergonomic component authoring.',
      'Its main tradeoffs usually involve template preference, ecosystem breadth compared with React, and choosing between the Options API and the newer Composition API when reading older versus newer codebases.',
    ],
  },
] as const

const coreConceptSections: readonly DocSection[] = [
  {
    id: 'core-key-ideas',
    title: 'Overview and Key Ideas',
    paragraphs: [
      'Vue follows a declarative model: application state drives rendered output. Instead of manually mutating the DOM, developers update reactive state and let Vue reconcile the interface.',
      'The key ideas are component composition, one-way data flow for props, event-based communication upward, and a reactivity system that tracks dependencies between state and rendered output.',
    ],
  },
  {
    id: 'core-components',
    title: 'Single-File Components',
    paragraphs: [
      'A common Vue unit is the Single-File Component, typically stored in a `.vue` file. It can colocate template, script, and style, which makes a component easy to inspect as one document.',
      'This structure is one of Vue\'s defining ergonomics. It keeps markup-like UI structure readable while still allowing JavaScript or TypeScript logic to live close to the rendered output.',
    ],
  },
  {
    id: 'core-syntax',
    title: 'Core Syntax',
    paragraphs: [
      'Vue templates use familiar HTML-like syntax extended with directives such as `v-if`, `v-for`, `v-bind`, and `v-model`. These directives express conditional rendering, iteration, attribute binding, and form synchronization directly in template markup.',
      'Event handling is usually written with `@click` and related shorthand. Interpolation with double braces inserts reactive values into the template, while bound attributes and class bindings keep DOM output connected to component state.',
    ],
  },
  {
    id: 'core-reactivity',
    title: 'Reactivity Model',
    paragraphs: [
      'Vue\'s reactivity system is a central design feature rather than an add-on. Primitives such as `ref`, `reactive`, `computed`, and `watch` let developers model local state, structured state, derived values, and side-effect reactions.',
      'This gives Vue a more explicitly reactive feel than frameworks whose mental model is centered primarily on rerendering function components. Many teams find that clarity useful for reasoning about derived state and dependency tracking.',
    ],
  },
  {
    id: 'core-apis',
    title: 'APIs and Authoring Styles',
    paragraphs: [
      'Modern Vue commonly uses the Composition API, often with `script setup`, to organize state and behavior through composable primitives. Older codebases may still use the Options API, which groups configuration by fields such as `data`, `computed`, `methods`, and lifecycle hooks.',
      'Both authoring styles are valid, but newer Vue guidance generally emphasizes the Composition API for flexibility and composability. That difference matters when reading documentation, onboarding into a legacy codebase, or comparing example code across versions and teams.',
    ],
  },
  {
    id: 'core-ecosystem',
    title: 'Ecosystem and Architecture',
    paragraphs: [
      'Vue\'s ecosystem often feels more coordinated than some library-first alternatives. Vue Router is the standard routing layer, Pinia is the current official state management recommendation, and the development toolchain is designed around Vue\'s component model.',
      'For application architecture, this means teams can adopt a cohesive baseline quickly. The framework gives enough flexibility for different project sizes while still offering a clear happy path for common frontend concerns.',
    ],
  },
  {
    id: 'core-use-cases',
    title: 'Use Cases',
    paragraphs: [
      'Vue is frequently used for admin panels, SaaS products, dashboards, content platforms, embedded app sections inside larger server-rendered sites, and greenfield SPAs where the team wants strong developer ergonomics without a heavyweight setup.',
      'It also works well for progressive enhancement because it can be introduced incrementally rather than requiring an all-or-nothing rewrite from the beginning.',
    ],
  },
  {
    id: 'core-tradeoffs',
    title: 'Tradeoffs',
    paragraphs: [
      'Vue\'s template-first style is a strength for many teams, but developers who prefer JavaScript-only rendering may still favor JSX-heavy workflows. The ecosystem is strong, yet the market size and third-party library breadth are still often compared against React\'s larger surface area.',
      'Another tradeoff is historical variation. Because Vue has evolved through multiple major API styles, teams sometimes have to understand both Options API patterns and Composition API patterns when maintaining mixed-age codebases.',
    ],
  },
  {
    id: 'core-compare',
    title: 'Compare and Contrast References',
    paragraphs: [
      'Vue is commonly compared with React for framework cohesion versus ecosystem freedom, with Svelte for runtime reactivity versus compiler-first design, and with Angular for lightweight flexibility versus heavier built-in structure.',
      'Those comparisons are useful because they reveal Vue\'s place in the frontend spectrum: more integrated than a bare UI library, less heavy than a highly opinionated enterprise framework, and more runtime-centric than compiler-first approaches.',
    ],
  },
] as const

const examples: readonly ExampleSection[] = [
  {
    id: 'examples-component',
    title: 'Basic Component Example',
    description:
      'A small Single-File Component shows Vue\'s common authoring shape: reactive state in `script setup` and declarative rendering in the template.',
    snippets: [
      {
        label: 'Counter.vue',
        code: `<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)
</script>

<template>
  <button @click="count++">Count: {{ count }}</button>
</template>`,
      },
    ],
    takeaway:
      'This pattern captures Vue\'s core feel: state is explicit, events update it directly, and the template reflects the latest value.',
  },
  {
    id: 'examples-derived',
    title: 'Derived State Example',
    description:
      'Computed values are a standard way to model values derived from reactive inputs without manually recalculating them throughout the component.',
    snippets: [
      {
        label: 'PriceSummary.vue',
        code: `<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  items: Array<{ price: number }>
}>()

const total = computed(() =>
  props.items.reduce((sum, item) => sum + item.price, 0)
)
</script>

<template>
  <p>Total: {{ total }}</p>
</template>`,
      },
    ],
    takeaway:
      'Computed state keeps derivation logic close to the component while preserving a clean template.',
  },
  {
    id: 'examples-patterns',
    title: 'Architecture Snapshot',
    description:
      'A typical Vue application combines routing, component state, and shared stores through a coordinated ecosystem rather than many unrelated libraries.',
    snippets: [
      {
        label: 'Common Stack',
        code: `Vue core for components and reactivity
Vue Router for navigation
Pinia for shared application state
Vite for development and bundling
Nuxt when SSR or full app-platform behavior is desired`,
      },
    ],
    takeaway:
      'The ecosystem story is one of Vue\'s strongest practical advantages for teams that want a coherent starting architecture.',
  },
] as const

const glossaryTerms: readonly GlossaryTerm[] = [
  {
    term: 'Vue.js',
    definition: 'A progressive JavaScript framework for building reactive user interfaces with components.',
  },
  {
    term: 'Single-File Component',
    definition: 'A `.vue` file that colocates template, script, and optionally style for one component.',
  },
  {
    term: 'Composition API',
    definition: 'Vue\'s modern authoring style built around functions such as `ref`, `reactive`, `computed`, and lifecycle hooks.',
  },
  {
    term: 'Options API',
    definition: 'An older but still valid Vue component style organized around fields such as `data`, `computed`, and `methods`.',
  },
  {
    term: 'ref',
    definition: 'A reactive primitive for storing a value that updates dependents when the value changes.',
  },
  {
    term: 'reactive',
    definition: 'A Vue helper for creating reactive proxy objects from structured state.',
  },
  {
    term: 'computed',
    definition: 'A derived reactive value that updates when its dependencies change.',
  },
  {
    term: 'watch',
    definition: 'A Vue primitive for responding to reactive value changes with side effects.',
  },
  {
    term: 'Directive',
    definition: 'A special template marker such as `v-if` or `v-for` that adds reactive behavior to markup.',
  },
  {
    term: 'Prop',
    definition: 'Read-only input passed from a parent component to a child component.',
  },
  {
    term: 'Emit',
    definition: 'A component event sent upward so parent components can react to child behavior.',
  },
  {
    term: 'Pinia',
    definition: 'The official state management library recommended for shared Vue application state.',
  },
] as const

const helpStyles = `
.vue-js-help-page {
  min-height: 100dvh;
  background: #c0c0c0;
  padding: 0;
  color: #000000;
  font-family: "MS Sans Serif", Tahoma, "Segoe UI", sans-serif;
}

.vue-js-help-window {
  width: 100%;
  min-height: 100dvh;
  display: flex;
  flex-direction: column;
  box-sizing: border-box;
  background: #c0c0c0;
  border-top: 2px solid #ffffff;
  border-left: 2px solid #ffffff;
  border-right: 2px solid #404040;
  border-bottom: 2px solid #404040;
}

.vue-js-help-titlebar {
  position: relative;
  display: flex;
  align-items: center;
  padding: 2px 4px;
  background: linear-gradient(90deg, #000080 0%, #1084d0 100%);
  color: #ffffff;
  font-size: 13px;
  font-weight: 700;
}

.vue-js-help-titletext {
  position: absolute;
  left: 50%;
  transform: translateX(-50%);
  font-size: 16px;
  white-space: nowrap;
}

.vue-js-help-controls {
  display: flex;
  gap: 2px;
  margin-left: auto;
}

.vue-js-help-control {
  width: 18px;
  height: 16px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-top: 1px solid #ffffff;
  border-left: 1px solid #ffffff;
  border-right: 1px solid #404040;
  border-bottom: 1px solid #404040;
  background: #c0c0c0;
  color: #000000;
  font-size: 11px;
  line-height: 1;
  text-decoration: none;
}

.vue-js-help-tabs {
  display: flex;
  gap: 1px;
  padding: 6px 8px 0;
  background: #c0c0c0;
}

.vue-js-help-tab {
  border-top: 1px solid #ffffff;
  border-left: 1px solid #ffffff;
  border-right: 1px solid #404040;
  border-bottom: none;
  background: #b6b6b6;
  padding: 5px 10px 4px;
  font-size: 12px;
  cursor: pointer;
}

.vue-js-help-tab.is-active {
  position: relative;
  top: 1px;
  background: #ffffff;
}

.vue-js-help-main {
  flex: 1;
  min-height: 0;
  display: grid;
  grid-template-columns: 240px 1fr;
  border-top: 1px solid #404040;
  background: #ffffff;
}

.vue-js-help-toc {
  overflow: auto;
  padding: 12px;
  background: #f2f2f2;
  border-right: 1px solid #808080;
}

.vue-js-help-toc-title {
  margin: 0 0 10px;
  font-size: 12px;
  font-weight: 700;
}

.vue-js-help-toc-list {
  margin: 0;
  padding: 0;
  list-style: none;
}

.vue-js-help-toc-list li {
  margin: 0 0 8px;
}

.vue-js-help-toc-list a {
  color: #000000;
  font-size: 12px;
  text-decoration: none;
}

.vue-js-help-content {
  overflow: auto;
  padding: 14px 20px 20px;
}

.vue-js-help-doc-title {
  margin: 0 0 12px;
  font-size: 20px;
  font-weight: 700;
}

.vue-js-help-doc-subtitle {
  margin: 0 0 12px;
  font-size: 12px;
}

.vue-js-help-section {
  margin: 0 0 20px;
  scroll-margin-top: 12px;
}

.vue-js-help-heading {
  margin: 0 0 8px;
  font-size: 16px;
  font-weight: 700;
}

.vue-js-help-subheading {
  margin: 0 0 6px;
  font-size: 13px;
  font-weight: 700;
}

.vue-js-help-content p,
.vue-js-help-content li {
  font-size: 12px;
  line-height: 1.5;
}

.vue-js-help-content p {
  margin: 0 0 10px;
}

.vue-js-help-content ul {
  margin: 0 0 10px 20px;
  padding: 0;
}

.vue-js-help-divider {
  margin: 14px 0;
  border: 0;
  border-top: 1px solid #d0d0d0;
}

.vue-js-help-codebox {
  margin: 6px 0 10px;
  padding: 8px;
  background: #f4f4f4;
  border-top: 2px solid #808080;
  border-left: 2px solid #808080;
  border-right: 2px solid #ffffff;
  border-bottom: 2px solid #ffffff;
}

.vue-js-help-codebox code {
  display: block;
  white-space: pre-wrap;
  font-family: "Courier New", Courier, monospace;
  font-size: 12px;
}

@media (max-width: 900px) {
  .vue-js-help-main {
    grid-template-columns: 1fr;
  }

  .vue-js-help-toc {
    border-right: none;
    border-bottom: 1px solid #808080;
  }

  .vue-js-help-titletext {
    position: static;
    transform: none;
    margin: 0 auto 0 0;
    padding-left: 4px;
    white-space: normal;
  }
}
`

const tabs: Array<{ id: TabId; label: string }> = [
  { id: 'big-picture', label: 'The Big Picture' },
  { id: 'core-concepts', label: 'Core Concepts' },
  { id: 'examples', label: 'Examples' },
  { id: 'glossary', label: 'Glossary' },
]

const sectionLinks: Record<TabId, Array<{ id: string; label: string }>> = {
  'big-picture': bigPictureSections.map((section) => ({ id: section.id, label: section.title })),
  'core-concepts': coreConceptSections.map((section) => ({ id: section.id, label: section.title })),
  examples: examples.map((section) => ({ id: section.id, label: section.title })),
  glossary: [{ id: 'glossary-terms', label: 'Terms' }],
}

function isTabId(value: string | null): value is TabId {
  return value === 'big-picture' || value === 'core-concepts' || value === 'examples' || value === 'glossary'
}

export default function VueJsPage(): JSX.Element {
  const location = useLocation()
  const navigate = useNavigate()
  const [searchParams, setSearchParams] = useSearchParams()
  const [activeTab, setActiveTab] = useState<TabId>(() => {
    const tab = searchParams.get('tab')
    return isTabId(tab) ? tab : 'big-picture'
  })

  const activeTabLabel = tabs.find((tab) => tab.id === activeTab)?.label ?? 'The Big Picture'

  useEffect(() => {
    const nextParams = new URLSearchParams(searchParams)
    if (nextParams.get('tab') !== activeTab) {
      nextParams.set('tab', activeTab)
      setSearchParams(nextParams, { replace: true })
    }
    document.title = `Vue.js (${activeTabLabel})`
  }, [activeTab, activeTabLabel, searchParams, setSearchParams])

  const handleMinimize = () => {
    const minimizedTask = {
      id: `help:${location.pathname}`,
      title: 'Vue.js',
      url: `${location.pathname}${location.search}${location.hash}`,
      kind: 'help',
    }
    const rawTasks = window.localStorage.getItem(MINIMIZED_HELP_TASKS_KEY)
    const parsedTasks = rawTasks ? (JSON.parse(rawTasks) as Array<{ id: string }>) : []
    const nextTasks = [...parsedTasks.filter((task) => task.id !== minimizedTask.id), minimizedTask]
    window.localStorage.setItem(MINIMIZED_HELP_TASKS_KEY, JSON.stringify(nextTasks))

    const historyState = window.history.state as { idx?: number } | null
    if (historyState?.idx && historyState.idx > 0) {
      void navigate(-1)
      return
    }
    void navigate('/algoViz')
  }

  return (
    <div className="vue-js-help-page">
      <style>{helpStyles}</style>
      <div className="vue-js-help-window" role="presentation">
        <header className="vue-js-help-titlebar">
          <span className="vue-js-help-titletext">Vue.js</span>
          <div className="vue-js-help-controls">
            <button className="vue-js-help-control" type="button" aria-label="Minimize" onClick={handleMinimize}>
              _
            </button>
            <Link to="/algoViz" className="vue-js-help-control" aria-label="Close">
              X
            </Link>
          </div>
        </header>

        <div className="vue-js-help-tabs" role="tablist" aria-label="Sections">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              type="button"
              className={`vue-js-help-tab ${activeTab === tab.id ? 'is-active' : ''}`}
              onClick={() => setActiveTab(tab.id)}
              role="tab"
              aria-selected={activeTab === tab.id}
            >
              {tab.label}
            </button>
          ))}
        </div>

        <div className="vue-js-help-main">
          <aside className="vue-js-help-toc" aria-label="Table of contents">
            <h2 className="vue-js-help-toc-title">Contents</h2>
            <ul className="vue-js-help-toc-list">
              {sectionLinks[activeTab].map((section) => (
                <li key={section.id}>
                  <a href={`#${section.id}`}>{section.label}</a>
                </li>
              ))}
            </ul>
          </aside>

          <main className="vue-js-help-content">
            <h1 className="vue-js-help-doc-title">Vue.js</h1>
            <p className="vue-js-help-doc-subtitle">
              Manual-style reference covering overview, key ideas, core syntax, APIs, ecosystem, architecture, use cases,
              tradeoffs, and examples.
            </p>

            {activeTab === 'big-picture' &&
              bigPictureSections.map((section, index) => (
                <Fragment key={section.id}>
                  <section id={section.id} className="vue-js-help-section">
                    <h2 className="vue-js-help-heading">{section.title}</h2>
                    {section.paragraphs.map((paragraph) => (
                      <p key={paragraph}>{paragraph}</p>
                    ))}
                  </section>
                  {index < bigPictureSections.length - 1 && <hr className="vue-js-help-divider" />}
                </Fragment>
              ))}

            {activeTab === 'core-concepts' &&
              coreConceptSections.map((section) => (
                <section key={section.id} id={section.id} className="vue-js-help-section">
                  <h2 className="vue-js-help-heading">{section.title}</h2>
                  {section.paragraphs.map((paragraph) => (
                    <p key={paragraph}>{paragraph}</p>
                  ))}
                </section>
              ))}

            {activeTab === 'examples' &&
              examples.map((example) => (
                <section key={example.id} id={example.id} className="vue-js-help-section">
                  <h2 className="vue-js-help-heading">{example.title}</h2>
                  <p>{example.description}</p>
                  {example.snippets.map((snippet) => (
                    <Fragment key={`${example.id}-${snippet.label}`}>
                      <h3 className="vue-js-help-subheading">{snippet.label}</h3>
                      <div className="vue-js-help-codebox">
                        <code>{snippet.code}</code>
                      </div>
                    </Fragment>
                  ))}
                  <p>
                    <strong>Takeaway:</strong> {example.takeaway}
                  </p>
                </section>
              ))}

            {activeTab === 'glossary' && (
              <section id="glossary-terms" className="vue-js-help-section">
                <h2 className="vue-js-help-heading">Glossary</h2>
                {glossaryTerms.map((item) => (
                  <p key={item.term}>
                    <strong>{item.term}:</strong> {item.definition}
                  </p>
                ))}
              </section>
            )}
          </main>
        </div>
      </div>
    </div>
  )
}
